name: Run Build

on:
  workflow_dispatch:
    inputs:
      app_name:
        type: string
        default: 'My-Prism-App'
        required: false
        description: "Type the name of your build."

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          bash build.sh --platform Android --project-name ${{ github.event.inputs.app_name }}

      # CLI call to simulated upload process
      - name: Upload
        run: |
          bash upload.sh build/android