name: Run Build

on:
  
  workflow_dispatch:
    inputs:
      app_name:
        type: string
        default: 'My-Prism-App'
        required: false
        description: "Type the name of your build."
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  APP_NAME: ${{ github.event.inputs.app_name || github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Version
        run: |
          VERSION="build-${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          bash build.sh --platform Android --project-name ${{ env.APP_NAME }}

      # CLI call to simulated upload process
      - name: Upload
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          bash upload.sh android build/Android/${{ env.APP_NAME }}.apk